[package]
name = "codegen_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
pmutil = "0.5.1"
proc-macro2 = "1"
swc_macros_common = "0.3.4"

[dependencies.syn]
features = ["fold"]
version = "1"